title: Chloe Li 
logo: "/images/logo.jpg?raw=true"
description: >
 Computer Science major, Integrated Digital Media/Math Minor
 <br><br>
 B.S, New York University
 <br><br>
 <a href="https://www.linkedin.com/in/ziqing-li-721293192/"> LinkedIn Profile</a>


theme: jekyll-theme-minimal
